package API::Model::APIDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'API::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=carneirao',
        user => 'carneirao',
        password => 'crinus666',
    }
);

=head1 NAME

API::Model::APIDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<API>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<API::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.63

=head1 AUTHOR

carneirao

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut




1;
